name: 'Maven setup'
description: 'Maven setup'
inputs:
  java-version: 
    description: 'Java version'
    required: true
    default: '11'
  private-ssh-key:
    description: 'Private ssh key'
    required: false
    default: ''
  java-setup-cache:
    description: 'Java setup cache'
    required: false
    default: 'maven'
runs:
  using: "composite"
  steps:
    - name: Configure Git User
      shell: bash
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "support@actonomy.com"
        git config --global author.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --global author.name "${GITHUB_ACTOR}"
    - name: Configure ssh key
      if: inputs.private-ssh-key != ''
      shell: bash
      # printf is builtin and won't show up in ps
      run: |
        mkdir ~/.ssh/
        printf %s "$SSH_KEY" | base64 -d > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
      env:
        SSH_KEY: ${{ inputs.private-ssh-key }}
    - name: Setup java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java-version }}
        cache: ${{ inputs.java-setup-cache }}
    - name: Maven settings
      uses: Actonomy/maven-settings-xml-action@v20
      with:
        servers: '[{"id": "actonomy","username": "${env.NEXUS_ACTO_USER}","password": "${env.NEXUS_ACTO_PASS}","configuration": {"httpConfiguration": {"all": {"usePreemptive": "true"}}}},{"id": "github","username": "git"}]'
        mirrors: '[{"id": "actonomy", "mirrorOf": "*", "url": "https://nexus.actonomy.be/content/groups/public/"}]'
        repositories: '[{"id": "central", "name": "Maven Central", "url": "http://central.invalid", "releases": {"enabled": "true"}, "snapshots": {"enabled": "true"}}]'
        plugin_repositories: '[{"id": "central", "name": "Maven Central", "url": "http://central.invalid", "releases": {"enabled": "true"}, "snapshots": {"enabled": "true"}}]'
